### ISSUE TITLE
Please release new version

### ISSUE THREAD

**Issue by erikd** [fumieval/bindings-portaudio#13]
The version on github exposes a `System.PortAudio` module, but the version on Hackage does not. Would be nice to see an updated version on Hackage.

**Comment by fumieval** [comment]
Oh, I've completely forgotten about it... going to upload as soon as I finish testing.

**Comment by fumieval** [comment]
done

**Comment by erikd** [comment]
Confirmed that `System.PortAudio` module is indeed available.

Closing this. Thanks!
