### ISSUE TITLE
Suggestion: Add a way to check if the stream is finished to System.PortAudio

### ISSUE THREAD

**Issue by ChristopherKing42** [fumieval/bindings-portaudio#15]
I find the System.PortAudio module quite handy! I suggest adding a way to see if the stream is finished to it. Currently, the only way to figure out if the stream is done playing yet is to try to figure out the timing.

Perhaps the module should expose a "Stream" object, which can be stopped, started, and checked if finished. I also see that there is a way to make callbacks that are fired when the stream is finished, so that would be helpful too!

**Comment by fumieval** [comment]
Added more APIs: https://github.com/fumieval/bindings-portaudio/commit/6b05506e7ba55e90b2ee1886921197547c14487e

I hope this is what you wanted. I can release a new version shortly

**Comment by ChristopherKing42** [comment]
This is exactly what I was thinking! Thank you!
