### ISSUE TITLE
Suggestion: use 2D arrays instead of vectors

### ISSUE THREAD

**Issue by ChristopherKing42** [fumieval/bindings-portaudio#16]
Currently, the library requires you to have a type constructor that is storable, applicative, and foldable. Moreover, you can't really make it variable length, so you need to hardcode the number of channels.

I suggest an alternative. Use a 2D array from [here](https://hackage.haskell.org/package/array-0.5.4.0/docs/Data-Array-Storable.html). The one dimension is time, and the other is the channel index. Specifically, it would use `StorableArray (Int, Int) a` where `a` is the sample type. (Also, `Storable` would become a superclass of the portaudio sample class to make the type signatures easier.) You might need to use [unsafeForeignPtrToStorableArray](https://hackage.haskell.org/package/array-0.5.4.0/docs/Data-Array-Unsafe.html#v:unsafeForeignPtrToStorableArray).

Alternatively, simple lists could be used. The type would be `[f a]` for foldable f and sample type `a`, which would then be converted to `[a]`. This list is then written to an array using [pokeArray](http://hackage.haskell.org/package/base-4.14.0.0/docs/Foreign-Marshal-Array.html#v:pokeArray).

**Comment by ChristopherKing42** [comment]
For the array suggestion, you could even make the channel index polymorphic. That is, instead of `(Int, Int)`, it would be `Ix i => (Int, i)`. The user could still make `i` be `Int`, but they could also use something like `data Channel = Left | Right` or what not. The functions needed to convert arrays to pointers do not care what index you use as long as it is `Ix`.

**Comment by fumieval** [comment]
I'm not a big fan of using Arrays or lists; there's a deliberate design choice of using a storable vector of static length data (e.g. V2), because it doesn't make sense to have dynamically changing number of channels in a stream. It also helps to have cache-friendly efficient operations.

**Comment by ChristopherKing42** [comment]
Storable Arrays can not change length in any dimension. Also, the current library does not guarantee static length, since Foldables can have a length that is different than the number of items they physically contain, perhaps in a variable way. For example, you can have `data Foo a = Foo Int a`, with `toList (Foo n a) = replicate n a`.

**Comment by ChristopherKing42** [comment]
If you wanted the length to be encoded in the type, you could use arrays where the bounds for the channel are `(minBound, maxBound)`, or use [fixed-vector](https://hackage.haskell.org/package/fixed-vector) which provides [this typeclass](https://hackage.haskell.org/package/fixed-vector-1.2.0.0/docs/Data-Vector-Fixed.html#t:Vector) specifically for fixed length vector types.

**Comment by fumieval** [comment]
I don't want 2D arrays because of the lack of API and you'll have to write elements one by one, for each channel. Fixed length vectors from the [linear](https://hackage.haskell.org/package/linear) package are intended ones right now.

**Comment by ChristopherKing42** [comment]
Okay, I think I understand why the library is the way it is now. I'll just close this issue.
